#!/bin/bash

config=kona-perf_defconfig

MAKE_PATH=../prebuilts/build-tools/bin/
CROSS_COMPILE=../prebuilts/gcc/bin/aarch64-linux-android-
KERNEL_ARCH=arm64
KERNEL_OUT=../kernel_out
export KERNEL_SRC=${KERNEL_OUT}
export CLANG_TRIPLE=aarch64-linux-gnu-
OUT_DIR=${KERNEL_OUT}
ARCH=${KERNEL_ARCH}
TARGET_INCLUDES=${TARGET_KERNEL_MAKE_CFLAGS}
TARGET_LINCLUDES=${TARGET_KERNEL_MAKE_LDFLAGS}

TARGET_KERNEL_MAKE_ENV+="CC=../prebuilts/clang/bin/clang"

${MAKE_PATH}make O=${OUT_DIR} ${TARGET_KERNEL_MAKE_ENV} LLVM_IAS=1 HOSTLDFLAGS="${TARGET_LINCLUDES}" ARCH=${ARCH} CROSS_COMPILE=${CROSS_COMPILE} NM=llvm-nm OBJCOPY=llvm-objcopy OBJDUMP=llvm-objdump STRIP=llvm-strip -j16 LLVM_IAS=1 vendor/$config

# cd ${KERNEL_DIR} && \
# ${MAKE_PATH}make O=${OUT_DIR} ${TARGET_KERNEL_MAKE_ENV} HOSTLDFLAGS="${TARGET_LINCLUDES}" ARCH=${ARCH} CROSS_COMPILE=${CROSS_COMPILE} menuconfig

cd ${OUT_DIR} && \
${MAKE_PATH}make ARCH=${ARCH} CROSS_COMPILE=${CROSS_COMPILE} LLVM_IAS=1 HOSTCFLAGS="${TARGET_INCLUDES}" HOSTLDFLAGS="${TARGET_LINCLUDES}" O=${OUT_DIR} ${TARGET_KERNEL_MAKE_ENV} NM=llvm-nm OBJCOPY=llvm-objcopy OBJDUMP=llvm-objdump STRIP=llvm-strip LLVM_IAS=1 -j16
